### ISSUE TITLE
Fail to initialize client without any parameters

### ISSUE THREAD

**Issue by tsolakoua** [amadeus4dev/amadeus-node#114]
When the environmental variables AMADEUS_CLIENT_ID and AMADEUS_CLIENT_SECRET are present, the client fails to be initialized without any parameters and throws an authentication error `ArgumentError: Missing required argument: clientId`

### How to reproduce:
- Add your AMADEUS_CLIENT_ID and AMADEUS_CLIENT_SECRET as environmental variables
- Run the following code: 

```
var Amadeus = require('amadeus');

var amadeus = new Amadeus();

amadeus.shopping.flightOffersSearch.get({
    originLocationCode: 'SYD',
    destinationLocationCode: 'BKK',
    departureDate: '2021-11-01',
    adults: '2'
}).then(function(response){
  console.log(response.data);
}).catch(function(responseError){
  console.log(responseError.code);
});
```

**Comment by jIrwinCline** [comment]
I'm still facing this issue on 11.0.0. Any thoughts?

```
import Amadeus from 'amadeus'
import type { APIGatewayEvent, Context } from 'aws-lambda'

import { logger } from 'src/lib/logger'

interface AmadeusFlightOffer {
  itineraries: Array<{
    segments: Array<{
      departure: {
        iataCode: string
        at: string
      }
      arrival: {
        iataCode: string
        at: string
      }
      carrierCode: string
    }>
  }>
  price: {
    total: string
  }
  numberOfBookableSeats: number
}

interface FlightSearchParams {
  originLocationCode: string
  destinationLocationCode: string
  departureDate: string
  adults?: number
}

console.log(                                          <------ these come out fine
  '=== HERE ===',
  process.env.AMADEUS_API_KEY,
  process.env.AMADEUS_API_SECRET
)

const amadeus = new Amadeus({
  clientId: process.env.AMADEUS_API_KEY || '',
  clientSecret: process.env.AMADEUS_API_SECRET || '',
})

const fetchAmadeusFlights = async (params: FlightSearchParams) => {
  try {
    const response = await amadeus.shopping.flightOffersSearch.get({
      originLocationCode: params.originLocationCode,
      destinationLocationCode: params.destinationLocationCode,
      departureDate: params.departureDate,
      adults: String(params.adults || 1),
      max: '10',
    })

    return response.data as AmadeusFlightOffer[]
  } catch (error) {
    logger.error('Error fetching flights from Amadeus:', error)
    throw error
  }
}

const transformToItinerary = (flight: AmadeusFlightOffer) => {
  const segment = flight.itineraries[0].segments[0] // Taking first segment for simplicity
  return {
    airline: segment.carrierCode,
    departure: segment.departure.iataCode,
    arrival: segment.arrival.iataCode,
    departureTime: new Date(segment.departure.at),
    arrivalTime: new Date(segment.arrival.at),
    price: parseFloat(flight.price.total),
    seatsAvailable: flight.numberOfBookableSeats,
  }
}

export const handler = async (event: APIGatewayEvent, _context: Context) => {
  logger.info(`${event.httpMethod} ${event.path}: fetchFlights function`)

  try {
    // Parse query parameters
    const params = event.queryStringParameters || {}
    const searchParams: FlightSearchParams = {
      originLocationCode: params.origin?.toUpperCase() || '',
      destinationLocationCode: params.destination?.toUpperCase() || '',
      departureDate: params.date || '',
      adults: parseInt(params.adults || '1', 10),
    }

    // Validate required parameters
    if (
      !searchParams.originLocationCode ||
      !searchParams.destinationLocationCode ||
      !searchParams.departureDate
    ) {
      return {
        statusCode: 400,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          error:
            'Missing required parameters: origin, destination, and date are required',
        }),
      }
    }

    // Fetch flights from Amadeus
    const flights = await fetchAmadeusFlights(searchParams)

    // Transform to itineraries
    const itineraries = flights.map(transformToItinerary)

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: itineraries,
      }),
    }
  } catch (error) {
    logger.error('Error in fetchFlights:', error)
    return {
      statusCode: 500,
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        error: 'Internal server error',
      }),
    }
  }
}
```
console
```
api | ArgumentError: Missing required argument: clientId
api |     at initRequired (/workspace/node_modules/amadeus/src/amadeus/client/validator.js:78:24)
api |     at initializeClientCredentials (/workspace/node_modules/amadeus/src/amadeus/client/validator.js:50:28)
api |     at Validator.validateAndInitialize (/workspace/node_modules/amadeus/src/amadeus/client/validator.js:38:10)
api |     at new Client (/workspace/node_modules/amadeus/src/amadeus/client.js:46:21)
api |     at new Amadeus (/workspace/node_modules/amadeus/src/amadeus.js:65:19)
api |     at Object.<anonymous> (/workspace/api/src/services/amadeus/amadeus.ts:3:17)
api |     at Module._compile (node:internal/modules/cjs/loader:1562:14)
api |     at Object..js (node:internal/modules/cjs/loader:1699:10)
api |     at Module.load (node:internal/modules/cjs/loader:1313:32)
api |     at Function._load (node:internal/modules/cjs/loader:1123:12)
```
