### ISSUE TITLE
Amadeus Get Request Improper Promise Handling

### ISSUE THREAD

**Issue by elliott44k** [amadeus4dev/amadeus-node#191]
## Description

When using the Amadeus client get I receive this. While the call completes with no issues, the error seems to stem from some response not being handled correctly prior to it being served by the library.

When making the call I see this in the console
```

Warning: a promise was rejected with a non-error: [object Object]
    at EventEmitter.<anonymous> (/amadeus/lib/amadeus/client.js:231:18)
    at EventEmitter.emit (node:events:527:28)
    at Listener.<anonymous> (/node_modules/amadeus/lib/amadeus/client/listener.js:162:24)
    at IncomingMessage.emit (node:events:527:28)
    at emitCloseNT (node:internal/streams/destroy:138:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Followed by the correct data being given.

## Steps to Reproduce

1. Initialize Amadeus client
2. Call
3. `await amadeus.schedule.flights.get({carrierCode: carrierCode, flightNumber: flightNumber, scheduledDepartureDate: scheduledDepartureDate})`

__Expected Behavior:__ [What you expect to happen]
Correct promise handling and then a promise returned.

__Actual Behavior:__ [What actually happens]
The error, followed by the correct promise.

__Stable Behavior?__ [What percentage of the time does it reproduce?]
100%

## Versions
Node 18.*
Mac OS 12.6

**Comment by tsolakoua** [comment]
Hello @elliott44k, could you please send the full code you used? We cannot reproduce the error.

**Comment by tsolakoua** [comment]
Closing due to inactivity and not having enough information to investigate.

**Comment by andyszy** [comment]
I am consistently seeing this warning when calling Amadeus from my nextjs app back-end. Node version 18. However I'm not sure how to debug. Any ideas?
